services:
  cms:
    image: node:18-alpine
    container_name: cms
    ports:
      - "3002:3002"
    volumes:
      - .:/home/node/app
      - payload_node_modules:/home/node/app/node_modules
      - payload_uploads:/home/node/uploads
    working_dir: /home/node/app/
    command: sh -c "npm install && npm run dev"
    depends_on:
      - database
    environment:
      PORT: 3002
      NODE_ENV: development
      DATABASE_URI: mongodb://admin:admin@database/payload?authSource=admin
      PAYLOAD_SECRET: TESTING
      UPLOADS_DIR: /home/node/uploads
      TZ: ${TZ}

  database:
    container_name: database
    image: mongo:8.0.3
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=payload
    # command: mongod --quiet --logpath /dev/null
    # logging:
    #   driver: none

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: 'mongodb://admin:admin@database/payload?authSource=admin'
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - database

volumes:
  db:
  payload_node_modules:
