services:
  lerna:
    image: node:18-alpine
    container_name: lerna
    volumes:
      - "./:/home/node/app"
      - lerna_node_modules:/home/node/app/node_modules
    command: sh -c 'npm install'
    working_dir: /home/node/app

  web-next:
    extends:
      file: './packages/web-next/docker-compose.yml'
      service: web-next
    environment:
      - NEXT_PUBLIC_PUBLIC_URL=${DEV_URL}
      - CMS_API_URL=${CMS_API_URL}
      - CMS_API_KEY=${CMS_API_KEY}
    command: sh -c 'npm run dev'
    working_dir: /home/node/app/packages/web-next
    volumes: !override
      - ./:/home/node/app/
      - lerna_node_modules:/home/node/app/node_modules
      - web_next_node_modules:/home/node/app/packages/web-next/node_modules
    restart: unless-stopped
    depends_on:
      - lerna

  cms:
    extends:
      file: './packages/cms/docker-compose.yml'
      service: cms
    command: sh -c 'npm run dev'
    working_dir: /home/node/app/packages/cms
    volumes: !override
      - ./:/home/node/app/
      - lerna_node_modules:/home/node/app/node_modules
      - cms_node_modules:/home/node/app/packages/cms/node_modules
      - ./seeds:/home/node/seeds
      - ./uploads:/home/node/uploads
    restart: unless-stopped
    depends_on:
      - lerna

  database:
    extends:
      file: './packages/cms/docker-compose.yml'
      service: database
    restart: unless-stopped

  mongo-express:
    extends:
      file: './packages/cms/docker-compose.yml'
      service: mongo-express

  caddy:
    image: caddy:2.8.4-alpine
    container_name: caddy
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  lerna_node_modules:
  web_next_node_modules:
  cms_node_modules:
  caddy_data:
  caddy_config:
  db:
