backend:
  name: github
  repo: ametis70/portfolio

media_folder: 'static/images/uploads' # Media files will be stored in the repo under static/images/uploads
public_folder: '/images/uploads' # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: about
    label: About
    files:
      - label: General
        name: general
        file: 'about/general.json'
        fields:
          - { label: 'Full Name', name: fullname, widget: string, required: true }
          - { label: City, name: city, widget: string, required: true }
          - { label: Birthday, name: birthday, widget: datetime, required: true }
          - { label: About, name: about, widget: markdown, required: true }
      - label: Experience
        name: experience
        file: 'about/experience.json'
        fields:
          - label: Items
            name: items
            widget: list
            fields:
              - { label: Role, name: role, widget: string }
              - { label: Company, name: company, widget: string }
              - { label: Description, name: description, widget: markdown }
              - {
                  label: 'Start datetime',
                  name: start,
                  widget: datetime,
                  format: 'MM/YYYY',
                }
              - {
                  label: 'End datetime',
                  name: end,
                  widget: datetime,
                  required: false,
                  format: 'MM/YYYY',
                }
      - label: Skills
        name: skills
        file: 'about/skills.json'
        widget: list
        fields:
          - label: Categories
            name: categories
            widget: list
            fields:
              - { label: 'Category title', name: name, widget: string }
              - label: Items
                name: items
                widget: list
                fields:
                  - label: Item
                    name: item
                    widget: string
      - label: Education
        name: education
        file: 'about/education.json'
        widget: list
        fields:
          - label: College
            name: college
            widget: list
            fields:
              - { label: Title, name: name, widget: string }
              - { label: Start, name: start, widget: datetime }
              - { label: End, name: end, widget: datetime, required: false }
              - { label: School, name: school, widget: string }
              - { label: link, name: link, widget: string, required: false }
          - label: Certifications
            name: certifications
            widget: list
            fields:
              - { label: Title, name: name, widget: string }
              - { label: Start, name: start, widget: datetime }
              - { label: End, name: end, widget: datetime, required: false }
              - { label: School, name: school, widget: string }
              - { label: link, name: link, widget: string, required: false }
