#backend:
#  name: github
#  repo: ametis70/portfolio
#  branch: main

backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: 'static/images/uploads' # Media files will be stored in the repo under static/images/uploads
public_folder: '/images/uploads' # The src attribute for uploaded media will begin with /images/uploads

i18n:
  structure: multiple_folders
  locales: [en, es]
  default_locale: en

collections:
  - name: about
    label: About
    i18n: true
    create: false
    extension: json
    folder: cms/about/
    slug: about
    fields:
      - { label: 'title', name: 'title', widget: 'hidden', default: 'About' }
      - label: General
        name: general
        i18n: true
        widget: object
        fields:
          - {
              label: 'Full Name',
              name: fullname,
              widget: string,
              required: true,
              i18n: duplicate,
            }
          - { label: City, name: city, widget: string, required: true, i18n: duplicate }
          - {
              label: Birthday,
              name: birthday,
              widget: datetime,
              required: true,
              i18n: duplicate,
            }
          - { label: About, name: about, widget: markdown, required: true, i18n: true }
      - label: Experience
        name: experience
        i18n: true
        widget: object
        fields:
          - label: Items
            name: items
            widget: list
            i18n: true
            fields:
              - { label: Role, name: role, widget: string, i18n: true }
              - { label: Company, name: company, widget: string, i18n: duplicate }
              - { label: Description, name: description, widget: markdown, i18n: true }
              - {
                  label: 'Start',
                  name: start,
                  widget: datetime,
                  format: 'MM/YYYY',
                  i18n: duplicate,
                }
              - {
                  label: 'End',
                  name: end,
                  widget: datetime,
                  required: false,
                  format: 'MM/YYYY',
                  i18n: duplicate,
                }
      - label: Skills
        name: skills
        i18n: true
        widget: object
        fields:
          - label: Categories
            name: categories
            widget: list
            i18n: true
            fields:
              - { label: 'Category title', name: name, widget: string, i18n: true }
              - label: Items
                name: items
                widget: list
                i18n: true
                fields:
                  - label: Item
                    name: item
                    widget: string
                    i18n: true
      - label: Education
        name: education
        widget: object
        i18n: true
        fields:
          - label: College
            name: college
            i18n: true
            widget: list
            fields:
              - { label: Title, name: name, widget: string, i18n: true }
              - { label: Start, name: start, widget: datetime, i18n: duplicate }
              - {
                  label: End,
                  name: end,
                  widget: datetime,
                  required: false,
                  i18n: duplicate,
                }
              - { label: School, name: school, widget: string, i18n: true }
              - {
                  label: link,
                  name: link,
                  widget: string,
                  required: false,
                  i18n: duplicate,
                }
          - label: Certifications
            name: certifications
            widget: list
            i18n: true
            fields:
              - { label: Title, name: name, widget: string, i18n: true }
              - { label: Start, name: start, widget: datetime, i18n: duplicate }
              - {
                  label: End,
                  name: end,
                  widget: datetime,
                  required: false,
                  i18n: duplicate,
                }
              - { label: School, name: school, widget: string, i18n: true }
              - {
                  label: link,
                  name: link,
                  widget: string,
                  required: false,
                  i18n: duplicate,
                }
