/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
    mesh_1: THREE.Mesh
  }
  materials: {
    bake_house: THREE.MeshBasicMaterial
    bake_table: THREE.MeshBasicMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/3d/house.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.43730545, 0, -0.750748932]}>
        <mesh
          geometry={nodes.mesh_0.geometry}
          material={materials.bake_house}
          position={[-2.35780334, 0, -1.03397489]}
          scale={0.000275012921}
        />
      </group>
      <group position={[-0.000498339534, 0, -1.43170905]}>
        <mesh
          geometry={nodes.mesh_1.geometry}
          material={materials.bake_table}
          position={[-2.35780334, 0, -1.03397489]}
          scale={0.000275012921}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/3d/house.glb')
