/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import { useFrame } from '@react-three/fiber'
import useStore from '../../store'
import { useColorMode } from '@chakra-ui/react'
import theme from '../../theme'

type ActionName = 'spin'
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
    mesh_1: THREE.Mesh
  }
  animations: GLTFAction[]
}

type LogoModelProps = JSX.IntrinsicElements['group'] & {
  position: Array<number>
}

const LogoModel: React.FC<LogoModelProps> = ({ ...props }) => {
  const { colorMode } = useColorMode()

  const group = useRef<THREE.Group>()
  const innerGroup = useRef<THREE.Group>()
  const { nodes, animations } = useGLTF('/3d/logo.glb') as unknown as GLTFResult
  const { actions } = useAnimations<GLTFAction>(animations, group)

  const isHome = useStore((state) => state.isHome)
  const [changeVisibilityTimeout, setChangeVisibilityTimeout] = useState<number | null>(
    null,
  )
  const [isVisible, setVisible] = useState<boolean>(false)

  const darkMaterial = useRef<THREE.MeshBasicMaterial>(
    new THREE.MeshBasicMaterial({ color: theme.colors.amethyst['900'] }),
  )

  const lightMaterial = useRef<THREE.MeshBasicMaterial>(
    new THREE.MeshBasicMaterial({ color: theme.colors.amethyst['50'] }),
  )

  const [fillMaterial, setFillMaterial] = useState<THREE.MeshBasicMaterial | undefined>(
    lightMaterial.current,
  )
  const [strokeMaterial, setStrokeMaterial] = useState<
    THREE.MeshBasicMaterial | undefined
  >(darkMaterial.current)

  useEffect(() => {
    if (actions.spin) {
      actions.spin.getMixer().timeScale = 0.5
      actions.spin.play()
    }
  }, [])

  useEffect(() => {
    if (colorMode === 'dark') {
      setFillMaterial(darkMaterial.current)
      setStrokeMaterial(lightMaterial.current)
    } else if (colorMode === 'light') {
      setFillMaterial(lightMaterial.current)
      setStrokeMaterial(darkMaterial.current)
    }
  }, [colorMode])

  useEffect(() => {
    if (isHome) {
      const timer = window.setTimeout(() => setVisible(true), 1000)
      setChangeVisibilityTimeout(timer)
    } else {
      setVisible(false)
      if (changeVisibilityTimeout) {
        window.clearTimeout(changeVisibilityTimeout)
        setChangeVisibilityTimeout(null)
      }
    }
  }, [isHome, setChangeVisibilityTimeout])

  useFrame(({ mouse }) => {
    if (group.current && mouse) {
      group.current.position.x = THREE.MathUtils.lerp(
        group.current.position.x,
        props.position[0] - mouse.x * 0.33,
        0.01,
      )
      group.current.position.y = THREE.MathUtils.lerp(
        group.current.position.y,
        props.position[1] - mouse.y * 0.15,
        0.01,
      )
      group.current.rotation.z = THREE.MathUtils.lerp(
        group.current.rotation.z,
        -(mouse.x * 0.15),
        0.01,
      )
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="group" ref={innerGroup}>
        <mesh
          onBeforeRender={(renderer) => {
            renderer.clearDepth()
          }}
          geometry={nodes.mesh_0.geometry}
          material={fillMaterial}
          position={[-0.430760831, -0.355498135, -0.430760741]}
          scale={0.0000617687183}
          renderOrder={999}
          visible={isVisible}
        />
        <mesh
          geometry={nodes.mesh_1.geometry}
          material={strokeMaterial}
          position={[-0.430760831, -0.355498135, -0.430760741]}
          scale={0.0000617687183}
          renderOrder={1000}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/3d/logo.glb')

export default LogoModel
