/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import { useFrame } from '@react-three/fiber'
import useStore from '../../store'

type ActionName = 'spin'
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
    mesh_1: THREE.Mesh
  }
  materials: {
    white: THREE.MeshBasicMaterial
    amethyst_export: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

type LogoModelProps = JSX.IntrinsicElements['group'] & {
  position: Array<number>
}

const LogoModel: React.FC<LogoModelProps> = ({ ...props }) => {
  const group = useRef<THREE.Group>()
  const innerGroup = useRef<THREE.Group>()
  const { nodes, materials, animations } = (useGLTF(
    '/3d/logo.glb',
  ) as unknown) as GLTFResult
  const { actions } = useAnimations<GLTFAction>(animations, group)

  const [hide, setHide] = useState<boolean>(true)

  useEffect(() => {
    if (actions.spin) {
      actions.spin.getMixer().timeScale = 0.5
      actions.spin.play()
    }

    useStore.subscribe(
      (isHome: boolean | undefined) => {
        if (isHome === undefined) return

        if (isHome) {
          setTimeout(() => setHide(isHome), 1000)
        } else {
          setHide(isHome)
        }
      },
      (state) => state.isHome,
    )
  }, [])

  useFrame(({ mouse }) => {
    if (group.current) {
      group.current.position.x = THREE.MathUtils.lerp(
        group.current.position.x,
        props.position[0] - mouse.x * 0.33,
        0.01,
      )
      group.current.position.y = THREE.MathUtils.lerp(
        group.current.position.y,
        props.position[1] - mouse.y * 0.15,
        0.01,
      )
      group.current.rotation.z = THREE.MathUtils.lerp(
        group.current.rotation.z,
        -(mouse.x * 0.15),
        0.01,
      )
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="group" ref={innerGroup}>
        <mesh
          onBeforeRender={(renderer) => {
            renderer.clearDepth()
          }}
          geometry={nodes.mesh_0.geometry}
          material={materials.white}
          position={[-0.430760831, -0.355498135, -0.430760741]}
          scale={0.0000617687183}
          renderOrder={999}
          visible={hide}
        />
        <mesh
          geometry={nodes.mesh_1.geometry}
          material={materials.amethyst_export}
          position={[-0.430760831, -0.355498135, -0.430760741]}
          scale={0.0000617687183}
          renderOrder={999}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/3d/logo.glb')

export default LogoModel
