/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
    mesh_1: THREE.Mesh
  }
  materials: {
    white: THREE.MeshBasicMaterial
    amethyst_export: THREE.MeshBasicMaterial
  }
}

type ActionName = 'spin'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/3d/logo.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="group" position={[0, 0.161480635, 0]}>
        <mesh
          geometry={nodes.mesh_0.geometry}
          material={materials.white}
          position={[-0.430760831, -0.355498135, -0.430760741]}
          scale={0.0000617687183}
        />
        <mesh
          geometry={nodes.mesh_1.geometry}
          material={materials.amethyst_export}
          position={[-0.430760831, -0.355498135, -0.430760741]}
          scale={0.0000617687183}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/3d/logo.glb')
