/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

import Screen from './Screen'

export type PcGLTF = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
    mesh_1: THREE.Mesh
    mesh_2: THREE.Mesh
    mesh_3: THREE.Mesh
    mesh_4: THREE.Mesh
  }
  materials: {
    bake_pc: THREE.MeshBasicMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/3d/pc.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[-0.456037909, 0.699552476, -1.59474409]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <mesh
          geometry={nodes.mesh_0.geometry}
          material={nodes.mesh_0.material}
          position={[-0.318482935, -0.0488045439, -0.401600093]}
          scale={0.0000476903442}
        />
      </group>
      <group position={[-0.343402922, 0.699552476, -1.30966198]}>
        <mesh
          geometry={nodes.mesh_1.geometry}
          material={nodes.mesh_1.material}
          position={[-0.318482935, -0.0488045439, -0.401600093]}
          scale={0.0000476903442}
        />
      </group>
      <group position={[-0.4560377, 0.707373023, -1.3096621]}>
        <mesh
          geometry={nodes.mesh_2.geometry}
          material={nodes.mesh_2.material}
          position={[-0.318482935, -0.0488045439, -0.401600093]}
          scale={0.0000476903442}
        />
      </group>
      <group position={[-0.167695016, 0.702065587, -1.31413388]} scale={0.111169644}>
        <mesh
          geometry={nodes.mesh_3.geometry}
          material={nodes.mesh_3.material}
          position={[-0.318482935, -0.0488045439, -0.401600093]}
          scale={0.0000476903442}
        />
      </group>
      <Screen />
    </group>
  )
}

useGLTF.preload('/3d/pc.glb')
